
services:
  grafana:
    container_name: grafana
    image: grafana/grafana:12.1
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
    restart: unless-stopped
    user: '1000:1000'
    
  influx:
    container_name: influx
    user: '1000:1000'
    image: influxdb:3-core
    restart: unless-stopped
    command:
      - influxdb3
      - serve
      - --node-id=node0
      - --object-store=file
      - --data-dir=/var/lib/influxdb3/data
      - --plugin-dir=/var/lib/influxdb3/plugins
    volumes:
      - ./influx/:/var/lib/influxdb3/data:rw
      - ./influx/:/var/lib/influxdb3/plugins:rw

  influx-ui:
    container_name: ui
    image: influxdata/influxdb3-ui:1.4.0
    restart: unless-stopped

  nginx:
    image: nginx:1.28-alpine-slim
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run
    network: bridge

