[package]
name = "proxy-passer"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
dotenvy = "0.15.7"
reqwest = { version = "0.13.2", features = ["json", "query"] }
tokio = { version = "1.49.0", features = ["full"] }
